import { Router } from "express";
import createIdeaRoute from "./createIdeaRoute";
import getIdeasRoute from "./getIdeasRoute";
import getIdeaByIdRoute from "./getIdeaByIdOrTitleRoute";
import updateIdeaRoute from "./updateIdeaRoute";
import deleteIdeaRoute from "./deleteIdeaRoute";
import approveIdeaRoute from "./approveIdeaRoute";
import voteIdeaRoute from "./voteIdeaRoute";
import addCommentRoute from "./addCommentRoute";
import getIdeaVersionsRoute from "./getIdeaVersionsRoute";
import getPendingApprovalIdeasRoute from "./getPendingApprovalIdeasRoute";
import getIdeaByUserRoute from "./getIdeaByUserRoute";
const router = Router();

router.use("/", createIdeaRoute);
router.use("/", getIdeasRoute);
router.use("/", getIdeaByIdRoute);
router.use("/", updateIdeaRoute);
router.use("/", deleteIdeaRoute);
router.use("/", approveIdeaRoute);
router.use("/", voteIdeaRoute);
router.use("/", addCommentRoute);
router.use("/", getIdeaVersionsRoute);
router.use("/", getPendingApprovalIdeasRoute);
router.use("/", getIdeaByUserRoute);
export default router;
