export const PERMISSIONS = {
	CREATE_IDEA: "create:idea",
	EDIT_IDEA: "edit:idea",
	DELETE_IDEA: "delete:idea",
	APPROVE_IDEA: "approve:idea",
	VIEW_ALL_IDEAS: "view:all_ideas",
	MANAGE_USERS: "manage:users",
	CREATE_CATEGORY: "create:category",
	UPDATE_CATEGORY: "update:category",
	VIEW_CATEGORIES: "view:categories",
	VIEW_CATEGORY: "view:category",
	DELETE_CATEGORY: "delete:category",
	MANAGE_BADGES: "manage:badges",
	VIEW_ANALYTICS: "view_analytics",
	MANAGE_DEPARTMENTS: "manage:departments",
	VIEW_DEPARTMENT: "view:department",
	DELETE_USER: "delete:user",
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_PERMISSIONS = {
	user: [
		PERMISSIONS.CREATE_IDEA,
		PERMISSIONS.VIEW_DEPARTMENT,
		PERMISSIONS.DELETE_USER,
		PERMISSIONS.VIEW_CATEGORIES,
		PERMISSIONS.VIEW_CATEGORY,
	],
	moderator: [
		PERMISSIONS.CREATE_IDEA,
		PERMISSIONS.EDIT_IDEA,
		PERMISSIONS.VIEW_ALL_IDEAS,
		PERMISSIONS.VIEW_DEPARTMENT,
		PERMISSIONS.VIEW_CATEGORIES,
		PERMISSIONS.VIEW_CATEGORY,
	],
	department_head: [
		PERMISSIONS.CREATE_IDEA,
		PERMISSIONS.EDIT_IDEA,
		PERMISSIONS.APPROVE_IDEA,
		PERMISSIONS.VIEW_ALL_IDEAS,
		PERMISSIONS.VIEW_ANALYTICS,
		PERMISSIONS.MANAGE_DEPARTMENTS,
		PERMISSIONS.VIEW_DEPARTMENT,
		PERMISSIONS.VIEW_CATEGORIES,
		PERMISSIONS.VIEW_CATEGORY,
	],
	admin: Object.values(PERMISSIONS),
	owner: Object.values(PERMISSIONS),
};
